// Texto de la plantilla de autorización. Edita aquí para cambiar el contenido del PDF.

export const TITLE = "AUTORIZACIÓN PARA CONSULTA Y REPORTE";
export const SUBTITLE = "MACROPAY GUATEMALA, SOCIEDAD ANÓNIMA";

export const PARAGRAPHS = [
  "“CLÁUSULA DE CONSENTIMIENTO Y EXONERACIÓN DE RESPONSABILIDAD. Autorizo expresamente a MACROPAY GUATEMALA, SOCIEDAD ANÓNIMA (de ahora en adelante, LA EMPRESA) a consultar mi información y la de la empresa a la que represento en TransUnion Guatemala, S.A., entidades que prestan servicios de información, centrales de riesgo, burós de crédito y sociedades de información crediticia (de ahora en adelante, llamadas ENTIDADES DE INFORMACIÓN) que estime conveniente, para que se lleven a cabo investigaciones sobre mi comportamiento crediticio; y autorizo a LA EMPRESA para que pueda proporcionar todos mis datos personales y datos personales sensibles, así como los datos de la empresa a la que represento, a las ENTIDADES DE INFORMACIÓN. Autorizo expresamente a LA EMPRESA y a las ENTIDADES DE INFORMACIÓN a recopilar, difundir, distribuir y comercializar con terceros, por cualquier medio, mi información personal y de comportamiento crediticio, así como la información de la empresa a la que represento, con la finalidad de verificación y análisis para el otorgamiento crediticio. Esta autorización se otorga bajo reserva del derecho de actualizar y rectificar la información si se comprueba que los datos son erróneos, incompletos o inexactos. En virtud de lo autorizado en este documento y cláusula específica, resulta inaplicable lo estipulado en el Código Penal y la Ley de Acceso a la Información Pública, por lo que exonero de cualquier responsabilidad a LA EMPRESA y a las ENTIDADES DE INFORMACIÓN por la difusión, distribución y comercialización de mi información.",
  "Consiento que esta autorización tenga una vigencia de 3 años, contados a partir de hoy y, en su caso, mientras mantengamos relación jurídica. Acepto que este documento quede bajo propiedad de LA EMPRESA y/o de las ENTIDADES DE INFORMACIÓN consultadas para efectos de control y cumplimiento de la Ley de Acceso a la Información Pública.”",
];
